# create database logs
CREATE TABLE LOGS
   (USER_ID VARCHAR(20)    NOT NULL,
    TIME   TIMESTAMP	   NOT NULL,
    LOGGER  VARCHAR(200)    NOT NULL,
    LEVEL   VARCHAR(10)    NOT NULL,
    MESSAGE VARCHAR(1000)  NOT NULL
   );