EXECUTOR_NUMBER?=0
DOCKER_CMD := docker
box_name = $(notdir $(CURDIR))
USER := $(shell id -un)
container_name = $(box_name)-$(USER)-$(EXECUTOR_NUMBER)
reg := docker.io/sroegner
tag := $(reg)/$(box_name)
sshopts := -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i $(CURDIR)/../shared/insecure.pem

