\timing on
\o /dev/null

-- Query 1:
SELECT l_returnflag, l_linestatus, sum(l_quantity) AS sum_qty, sum(l_extendedprice) AS sum_base_price, sum(l_extendedprice * (1 - l_discount)) AS sum_disc_price, sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge, avg(l_quantity) AS avg_qty, avg(l_extendedprice) AS avg_price, avg(l_discount) AS avg_disc, count(*) AS count_order FROM lineitem WHERE (lineitem.l_shipdate <= '1998-11-30 00:00:00') GROUP BY lineitem.l_returnflag, lineitem.l_linestatus ORDER BY lineitem.l_returnflag, lineitem.l_linestatus;

-- Query 2 (modified):
SELECT supplier.s_acctbal, supplier.s_name, nation.n_name, part.p_partkey, part.p_mfgr, supplier.s_address, supplier.s_phone, supplier.s_comment FROM (SELECT partsupp_1.ps_partkey, min(partsupp_1.ps_supplycost) AS minsuppcost FROM nation AS nation_1, region AS region_1, supplier AS supplier_1, partsupp AS partsupp_1 WHERE (supplier_1.s_nationkey = nation_1.n_nationkey) AND (nation_1.n_regionkey = region_1.r_regionkey) AND (region_1.r_name = 'AMERICA') AND (partsupp_1.ps_suppkey = supplier_1.s_suppkey) GROUP BY partsupp_1.ps_partkey) AS BIGDAWGAGGREGATE_1, partsupp, part, supplier, nation, region WHERE ((BIGDAWGAGGREGATE_1.minsuppcost) = partsupp.ps_supplycost) AND (partsupp.ps_partkey = BIGDAWGAGGREGATE_1.ps_partkey) AND ((part.p_type LIKE '%BRASS') AND (part.p_size = 14)) AND (part.p_partkey = partsupp.ps_partkey) AND (part.p_partkey = partsupp.ps_partkey) AND (supplier.s_suppkey = partsupp.ps_suppkey) AND (nation.n_nationkey = supplier.s_nationkey) AND (region.r_name = 'AMERICA') AND (region.r_regionkey = nation.n_regionkey) AND (region.r_regionkey = nation.n_regionkey) ORDER BY supplier.s_acctbal DESC, nation.n_name, supplier.s_name, part.p_partkey;

-- Query 3:
SELECT lineitem.l_orderkey, sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)) AS revenue, orders.o_orderdate, orders.o_shippriority FROM orders, customer, lineitem WHERE (orders.o_custkey = customer.c_custkey) AND (orders.o_orderdate < '1996-01-02') AND (customer.c_mktsegment = 'AUTOMOBILE') AND (lineitem.l_orderkey = orders.o_orderkey) AND (lineitem.l_shipdate > '1996-01-02') AND (lineitem.l_orderkey = orders.o_orderkey) GROUP BY lineitem.l_orderkey, orders.o_orderdate, orders.o_shippriority ORDER BY revenue DESC, orders.o_orderdate;

-- Query 4 (modified) -- updated :
SELECT orders.o_orderpriority, count(DISTINCT orders.o_orderkey) AS order_count FROM orders, lineitem WHERE ((orders.o_orderdate >= '1996-01-02') AND (orders.o_orderdate < '1996-04-02')) AND (lineitem.l_orderkey = orders.o_orderkey) AND (lineitem.l_commitdate < lineitem.l_receiptdate) GROUP BY orders.o_orderpriority ORDER BY orders.o_orderpriority;

-- Query 5:
SELECT nation.n_name, sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)) AS revenue FROM orders, lineitem, supplier, nation, customer, region WHERE (supplier.s_nationkey = customer.c_nationkey) AND ((orders.o_orderdate >= '1996-01-02') AND (orders.o_orderdate < '1997-01-02 00:00:00')) AND (lineitem.l_orderkey = orders.o_orderkey) AND (supplier.s_suppkey = lineitem.l_suppkey) AND (nation.n_nationkey = supplier.s_nationkey) AND (customer.c_custkey = orders.o_custkey) AND (region.r_regionkey = nation.n_regionkey) AND (region.r_name = 'AMERICA') AND (region.r_regionkey = nation.n_regionkey) GROUP BY nation.n_name ORDER BY revenue DESC;

-- Query 6:
SELECT sum(l_extendedprice * l_discount) AS revenue FROM lineitem WHERE ((lineitem.l_shipdate >= '1996-01-02') AND (lineitem.l_shipdate < '1997-01-02 00:00:00') AND (lineitem.l_discount >= 0.06) AND (lineitem.l_discount <= 0.08) AND (lineitem.l_quantity < 32));

-- Query 7: * MISSING SORT
SELECT n1.n_name, n2.n_name, date_part('year', lineitem.l_shipdate) AS datepartyearlineitem32, sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)) AS sumlineitemlextended11 FROM lineitem, supplier, orders, customer, nation AS n1, nation AS n2 WHERE (((n1.n_name = 'ARGENTINA') AND (n2.n_name = 'BRAZIL')) OR ((n1.n_name = 'BRAZIL') AND (n2.n_name = 'ARGENTINA'))) AND ((lineitem.l_shipdate >= '1995-01-01') AND (lineitem.l_shipdate <= '1996-12-31')) AND (supplier.s_suppkey = lineitem.l_suppkey) AND (orders.o_orderkey = lineitem.l_orderkey) AND (customer.c_custkey = orders.o_custkey) AND (n1.n_nationkey = supplier.s_nationkey) AND ((n1.n_name = 'ARGENTINA') OR (n1.n_name = 'BRAZIL')) AND (n1.n_nationkey = supplier.s_nationkey) AND ((n2.n_name = 'BRAZIL') OR (n2.n_name = 'ARGENTINA')) AND (n2.n_nationkey = customer.c_nationkey) AND (n2.n_nationkey = customer.c_nationkey) GROUP BY n1.n_name, n2.n_name, datepartyearlineitem32 ORDER BY n1.n_name, n2.n_name, datepartyearlineitem32;

-- Query 8: * MISSING SORT
SELECT date_part('year', orders.o_orderdate) AS datepartyearordersoo110, sum(CASE WHEN n2.n_name = 'ARGENTINA' THEN lineitem.l_extendedprice * (1 - lineitem.l_discount) ELSE 0 END) / sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)) AS sumCASEWHENn2nnameAR66 FROM orders, lineitem, part, supplier, customer, nation AS n1, nation AS n2, region WHERE ((orders.o_orderdate >= '1995-01-01') AND (orders.o_orderdate <= '1996-12-31')) AND (lineitem.l_orderkey = orders.o_orderkey) AND (part.p_type = 'SMALL PLATED BRASS') AND (part.p_partkey = lineitem.l_partkey) AND (part.p_partkey = lineitem.l_partkey) AND (supplier.s_suppkey = lineitem.l_suppkey) AND (customer.c_custkey = orders.o_custkey) AND (n1.n_nationkey = customer.c_nationkey) AND (n2.n_nationkey = supplier.s_nationkey) AND (region.r_name = 'AMERICA') AND (region.r_regionkey = n1.n_regionkey) AND (region.r_regionkey = n1.n_regionkey) GROUP BY datepartyearordersoo110 ORDER BY datepartyearordersoo110;

-- Query 9: * MISSING ORDER 
SELECT nation.n_name, date_part('year', orders.o_orderdate) AS datepartyearordersoo29, sum((lineitem.l_extendedprice * (1 - lineitem.l_discount)) - (partsupp.ps_supplycost * lineitem.l_quantity)) AS sumlineitemlextended102 FROM lineitem, part, partsupp, supplier, orders, nation WHERE (lineitem.l_partkey = part.p_partkey) AND (part.p_name LIKE '%chocolate%') AND ((partsupp.ps_partkey = lineitem.l_partkey) AND (partsupp.ps_suppkey = lineitem.l_suppkey)) AND (supplier.s_suppkey = lineitem.l_suppkey) AND (orders.o_orderkey = lineitem.l_orderkey) AND (nation.n_nationkey = supplier.s_nationkey) GROUP BY nation.n_name, datepartyearordersoo29 ORDER BY nation.n_name, datepartyearordersoo29 DESC;

-- Query 10:
SELECT customer.c_custkey, customer.c_name, sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)) AS revenue, customer.c_acctbal, nation.n_name, customer.c_address, customer.c_phone, customer.c_comment FROM lineitem, orders, customer, nation WHERE (lineitem.l_returnflag = 'R') AND (orders.o_orderkey = lineitem.l_orderkey) AND ((orders.o_orderdate >= '1996-05-02') AND (orders.o_orderdate < '1996-08-02 00:00:00')) AND (orders.o_orderkey = lineitem.l_orderkey) AND (customer.c_custkey = orders.o_custkey) AND (nation.n_nationkey = customer.c_nationkey) GROUP BY customer.c_custkey, customer.c_name, customer.c_acctbal, customer.c_phone, nation.n_name, customer.c_address, customer.c_comment ORDER BY revenue DESC;

-- Query 11 (modified): 
SELECT BIGDAWGAGGREGATE_2.ps_partkey, BIGDAWGAGGREGATE_2.sumpartsupppssupplyc63 FROM (SELECT partsupp.ps_partkey, sum(partsupp.ps_supplycost * (partsupp.ps_availqty)) AS sumpartsupppssupplyc63 FROM supplier, nation, partsupp WHERE (supplier.s_nationkey = nation.n_nationkey) AND (nation.n_name = 'CANADA') AND (partsupp.ps_suppkey = supplier.s_suppkey) GROUP BY partsupp.ps_partkey) AS BIGDAWGAGGREGATE_2, (SELECT sum(partsupp_1.ps_supplycost * (partsupp_1.ps_availqty)) * 0.00018 AS sumpartsupp1pssupply93 FROM supplier AS supplier_1, nation AS nation_1, partsupp AS partsupp_1 WHERE (supplier_1.s_nationkey = nation_1.n_nationkey) AND (nation_1.n_name = 'CANADA') AND (partsupp_1.ps_suppkey = supplier_1.s_suppkey)) AS BIGDAWGAGGREGATE_3 WHERE (BIGDAWGAGGREGATE_2.sumpartsupppssupplyc63 > BIGDAWGAGGREGATE_3.sumpartsupp1pssupply93) ORDER BY sumpartsupppssupplyc63 DESC;

-- Query 12: * MISSING ORDER
SELECT lineitem.l_shipmode, sum(CASE WHEN (orders.o_orderpriority = '1-URGENT') OR (orders.o_orderpriority = '2-HIGH') THEN 1 ELSE 0 END) AS sumCASEWHENordersoor137, sum(CASE WHEN (orders.o_orderpriority <> '1-URGENT') AND (orders.o_orderpriority <> '2-HIGH') THEN 1 ELSE 0 END) AS sumCASEWHENordersoor77 FROM lineitem, orders WHERE ((lineitem.l_shipmode IN ('SHIP', 'TRUCK')) AND (lineitem.l_commitdate < lineitem.l_receiptdate) AND (lineitem.l_shipdate < lineitem.l_commitdate) AND (lineitem.l_receiptdate >= '1996-01-02') AND (lineitem.l_receiptdate < '1997-01-02 00:00:00')) AND (orders.o_orderkey = lineitem.l_orderkey) GROUP BY lineitem.l_shipmode ORDER BY lineitem.l_shipmode;

-- Query 13 (modified) -- failed

-- Query 14:
SELECT 100.00 * sum(CASE WHEN part.p_type LIKE 'PROMO%' THEN lineitem.l_extendedprice * (1 - lineitem.l_discount) ELSE 0 END) / sum(lineitem.l_extendedprice * (1 - lineitem.l_discount)) AS promo_revenue FROM lineitem, part WHERE ((lineitem.l_shipdate >= '1996-01-02') AND (lineitem.l_shipdate < '1996-02-02 00:00:00')) AND (part.p_partkey = lineitem.l_partkey);

-- Query 15 (modified):
WITH revenue_s AS (SELECT l_suppkey AS supplier_no, sum(l_extendedprice * (1 - l_discount)) AS total_revenue FROM lineitem WHERE l_shipdate >= '1996-01-02' AND l_shipdate < '1996-04-02' GROUP BY l_suppkey) SELECT supplier.s_suppkey, supplier.s_name, supplier.s_address, supplier.s_phone, revenue_s.total_revenue FROM revenue_s, supplier, (SELECT max(revenue_s_1.total_revenue) AS max_total_revenue FROM revenue_s AS revenue_s_1) AS BIGDAWGAGGREGATE_1 WHERE (revenue_s.total_revenue = BIGDAWGAGGREGATE_1.max_total_revenue) AND (supplier.s_suppkey = revenue_s.supplier_no) ORDER BY supplier.s_suppkey;

-- Query 16 (modified):
SELECT part.p_brand, part.p_type, part.p_size, count(DISTINCT partsupp.ps_suppkey) AS supplier_cnt FROM partsupp, part, supplier WHERE (partsupp.ps_suppkey <> supplier.s_suppkey) AND (partsupp.ps_partkey = part.p_partkey) AND ((part.p_brand <> 'Brand#13') AND (part.p_type NOT LIKE 'MEDIUM%') AND (part.p_size IN (7, 1, 21, 14, 15, 4, 45, 41))) AND (supplier.s_comment LIKE '%Customer%Complaints%') GROUP BY part.p_brand, part.p_type, part.p_size ORDER BY supplier_cnt DESC, part.p_brand, part.p_type, part.p_size;

-- Query 17 -- too slow, skipping;

-- Query 18 (modified):
SELECT customer.c_name, customer.c_custkey, orders.o_orderkey, orders.o_orderdate, orders.o_totalprice, sum(lineitem.l_quantity) AS sum117 FROM orders, customer, lineitem, (SELECT lineitem_1.l_orderkey FROM lineitem AS lineitem_1 GROUP BY lineitem_1.l_orderkey HAVING sum(lineitem_1.l_quantity) > 310) AS BIGDAWGAGGREGATE_2 WHERE (lineitem.l_orderkey = BIGDAWGAGGREGATE_2.l_orderkey) AND (orders.o_orderkey = lineitem.l_orderkey) AND (orders.o_custkey = customer.c_custkey) GROUP BY orders.o_totalprice, orders.o_orderdate, customer.c_name, customer.c_custkey, orders.o_orderkey ORDER BY orders.o_totalprice DESC, orders.o_orderdate;
